### PR TITLE
added getyarn.io plugin

### PR DESCRIPTION
**Pull request by noreason**
yarn doesn't have an api so I had to 'scrape' the dom for a possible result. it's dirty, but it works. 

I had to pull in a new dependency (cheerio) because it seemed like a smarter idea than trying to parse the entire html response and do string manipulation to try and find the result. With cheerio, you're able to select elements (jQuery), so tl;dr is that if no element is returned than "No result found."

sadly, if they decide to change their markup at some point in the future, the plugin will have to be adjusted as well, but thus is life when scraping without an api I guess.

### CODE REVIEW

**Comment by mikerogne** [comment]
If willing, when you get time can you add some tests? Probably same tests as Youtube plugin or giphy or similar.

**Comment by noreason** [comment]
> If willing, when you get time can you add some tests? Probably same tests as Youtube plugin or giphy or similar.

Yeah no doubt. Would be a good time to get the hang of it.

**Comment by noreason** [comment]
test added

**Comment by mikerogne** [comment]
Awesome! Thanks @noreason!

**Pull request merged**
